config/routes.rb
Rails.application.routes.draw do
  # json api routes
  namespace :api do
    # endpoint for generating jwt
    post 'user_token' => 'user_token#create'

    # get 'test' => 'jobs#test_path'
    # post 'test' => 'jobs#test_path'

    resources :jobs, only: [:index, :create]
    resources :users, only: [:show, :create]
  end

  # html requests (routing handled by react)
  root 'application#index'
  get '*path', to: 'application#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/job.rb
class Job < ApplicationRecord
  belongs_to :user

  validates :title, presence: true
  validates :description, presence: true  
end

app/models/user.rb
class User < ApplicationRecord
  has_many :jobs, dependent: :destroy

  validates :name, presence: true,
      length: {maximum: 100, too_long: "The maximum allowed length is %{count}"}
  validates :email, presence: true,
      length: {maximum: 255, too_long: "The maximum allowed length is %{count}"},
      format: {with: /\A\S+@\S+\.\S+\Z/, message: "Must be a valid email"},
      uniqueness: {case_sensitive: false}

  has_secure_password
  validates :password, presence: true, length: {minimum: 8, too_short: "The minimum allowed length is %{count}"}
end

app/controllers/api/jobs_controller.rb
class Api::JobsController < ApplicationController
  before_action :authenticate_user, except: [:index]

  def index
    @jobs = Job.all
    render json: @jobs
  end

  # def test_path
  #   render json: {"Response": "Success!"}
  # end

  def create
    @job = current_user.jobs.new(params.require(:job).permit(:title, :description))
    if @job.save
      render json: @job, status: :created
    else
      render status: :bad_request
    end
  end
end

app/controllers/api/user_token_controller.rb
class Api::UserTokenController < Knock::AuthTokenController
end

app/controllers/api/users_controller.rb
class Api::UsersController < ApplicationController
  def show
    # @user = User.find(params[:id])
    # render json: @user
    if current_user
      render json: {user: current_user, jobs: current_user.jobs}
    else
      render json: {}, status: 404
    end
  end
  def create
    @user = User.new(params.require(:user).permit(:name, :email, :password, :password_confirmation))
    render json: @user
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Knock::Authenticable
  protect_from_forgery with: :null_session

  def index
    # Rails will route all GET requests to this action
    # the actual app routing will be handled by React
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/application/_header.html.erb
<header>
  <div id="navbar">
    <%= link_to "Jobs List", jobs_path %>
    <%= link_to "New Job", new_job_path %>

    <% if logged_in? %>
      <%= link_to "Profile", current_user %>
      <%= link_to "Log Out", logout_path, method: :delete %>
    <% else %>
      <%= link_to "Sign Up", new_user_path %>
      <%= link_to "Log In", login_path %>
    <% end %>
    
  </div>

  <div id="flash_container">
    <% flash.each do |key, message| %>
    <div class="flash <%= key %>">
      <%= message %>
    </div>
    <% end %>
  </div>
</header>

app/views/application/index.html.erb
<!--
Placeholder render file so rails doesn't complain
-->

app/views/jobs/index.html.erb
<h1>jobs#index</h1>

<% if not @jobs.empty? %>
<ul>
<% @jobs.each do |job| %>
  <li>
    <span><%= job.title %></span>
    <span><%= job.description %></span>
  </li>
<% end %>
</ul>
<% else %>
<div>No Posted Jobs</div>
<% end %>

app/views/jobs/new.html.erb
<h1>jobs#new</h1>

<%= form_for @job do |f| %>
  <%= f.label :title, "Job Title" %>
  <%= f.text_field :title %>
  <%= f.label :description %>
  <%= f.text_area :description %>
  <%= f.submit %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>JobPostr</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <div id="root"></div>
  <body>
    <%= yield %>
  </body>
  <%= javascript_pack_tag 'app' %>
</html>

app/views/users/new.html.erb
<h1>user#new</h1>
<%= form_for @user do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :email %>
  <%= f.email_field :email %>
  <%= f.label :password %>
  <%= f.password_field :password %>
  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %>

  <%= f.submit "Create Account" %>
<% end %>

app/views/users/show.html.erb
<h1>User page for: <%= @user.name %></h1>
<% if not @jobs.empty? %>
<ul>
<% @jobs.each do |job| %>
  <li>
    <span><%= job.title %></span>
    <span><%= job.description %></span>
  </li>
<% end %>
</ul>
<% else %>
<div>No Posted Jobs For <%= @user.name %></div>
<% end %>